services:

  stock_predict:
    build: 
      context: .
      dockerfile: src/serving/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - mlflow_data:/mlflow
    networks:
      minha-rede:
        ipv4_address: 172.18.0.8
    ports:
      - "8000:8000"
    command: uvicorn src.serving.app:app --host 0.0.0.0 --port 8000
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    command: "mlflow server --host 0.0.0.0 --port 5000"
    networks:
      minha-rede:
        ipv4_address: 172.18.0.4
    volumes:
      - mlflow_data:/mlflow
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/monitoring_config.yaml:/etc/prometheus/prometheus.yml
    networks:
      minha-rede:
        ipv4_address: 172.18.0.7
    depends_on:
      - stock_predict

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      minha-rede:
        ipv4_address: 172.18.0.6
    depends_on:
      - prometheus    
    volumes:
      - grafana_data:/var/lib/grafana 
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    networks:
      minha-rede:
        ipv4_address: 172.18.0.3
    ports:
      - "4200:4200"



volumes:      
  mlflow_data:
  grafana_data:

networks:
  minha-rede:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24