services:

  stock_predict:
    build: 
      context: .
      dockerfile: src/serving/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - mlflow_data:/mlflow
    ports:
      - "8000:8000"
    command: uvicorn src.serving.app:app --host 0.0.0.0 --port 8000
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    command: "mlflow server --host 0.0.0.0 --port 5000"
    volumes:
      - mlflow_data:/mlflow
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/monitoring_config.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - stock_predict

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus    
    volumes:
      - grafana_data:/var/lib/grafana 
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
  worker:
    image: prefecthq/prefect:3-latest  # <- troca build: . por isso
    command: prefect worker start --pool "default-agent-pool"
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    depends_on:
      - prefect-server

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
volumes:      
  mlflow_data:
  grafana_data: